// SPDX-License-Identifier: Apache-2.0
//
// Generated by `cux_ship deps update`. Do not edit by hand.
//
// The pins live here rather than in each consuming repository so that a bump is
// one `cux_ship` release instead of an edit in n projects — which is the whole
// reason this moved out of a per-project `tool/deps.lock`.
//
// Data, deliberately: a file containing nothing but pins diffs the way a
// lockfile does, and an upgrade shows exactly what it changed. `deps update`
// rewrites this file and nothing else, so it is not a program editing itself.
//
// **The checksums are not ceremony.** These files are downloaded and then
// executed, and a version pin alone only means "some build of 3.13.3" — the
// hash is what makes it a specific one.
//
// sops checksums come from the checksums.txt published with its release. age
// publishes sigstore proofs but no checksum file, so its hashes are computed
// from the downloads at update time — trust on first use, over HTTPS to GitHub.
// Re-pinning is therefore only as good as the fetch that did it: review the
// diff when a hash changes without a version changing with it.

/// One platform's build of one tool, and the hash it must have.
typedef ToolPin = ({
  String tool,
  String version,
  String platform,
  String sha256,
});

/// Every platform is pinned regardless of the machine that ran the update, so
/// a set written on a Mac still serves a Linux runner.
const depsPins = <ToolPin>[
  (
    tool: 'sops',
    version: '3.13.3',
    platform: 'darwin.arm64',
    sha256: 'b97c0d434aab577dc40310e8d22ff9e45eef4c80638ab978daae9b4681c59286',
  ),
  (
    tool: 'sops',
    version: '3.13.3',
    platform: 'darwin.amd64',
    sha256: '42162d5cef10b74fcf80a045a70e658d7ce6e63d6ea1be6f347e44015714468d',
  ),
  (
    tool: 'sops',
    version: '3.13.3',
    platform: 'linux.amd64',
    sha256: 'e5bec3346a873ae91d871550f3e698c1aad962aff462a080e40f25fde17fef6b',
  ),
  (
    tool: 'sops',
    version: '3.13.3',
    platform: 'linux.arm64',
    sha256: '53b0abacd38ef1b12a66d6c100956691b9cefce018d91f81e73ddf7438b94d77',
  ),
  (
    tool: 'sops',
    version: '3.13.3',
    platform: 'amd64.exe',
    sha256: 'a4a9a398858fe8b2ef72d9686d930bf7c5cece9be74ad83ac3b53cfdd70e6b1c',
  ),
  (
    tool: 'age',
    version: '1.3.1',
    platform: 'darwin-arm64',
    sha256: '01120ea2cbf0463d4c6bd767f99f3271bbed1cdc8a9aa718a76ba1fe4f01998b',
  ),
  (
    tool: 'age',
    version: '1.3.1',
    platform: 'darwin-amd64',
    sha256: '2b233301ad21ab7b1eabd9ae1198a164005fa4928fcdd745d47c39f8593209d7',
  ),
  (
    tool: 'age',
    version: '1.3.1',
    platform: 'linux-amd64',
    sha256: 'bdc69c09cbdd6cf8b1f333d372a1f58247b3a33146406333e30c0f26e8f51377',
  ),
  (
    tool: 'age',
    version: '1.3.1',
    platform: 'linux-arm64',
    sha256: 'c6878a324421b69e3e20b00ba17c04bc5c6dab0030cfe55bf8f68fa8d9e9093a',
  ),
  (
    tool: 'age',
    version: '1.3.1',
    platform: 'windows-amd64',
    sha256: 'c56e8ce22f7e80cb85ad946cc82d198767b056366201d3e1a2b93d865be38154',
  ),
];
