// SPDX-License-Identifier: Apache-2.0
//
// Decrypts a sops file and runs a command with the credentials in its
// environment.
//
//   cux_ship secrets exec -- tool/build.sh --release android
//   cux_ship secrets exec -- env
//
// **This is the only part of cux_ship that knows sops exists, and that is
// structural.** Every uploader reads plain environment variables and nothing
// else, so they work unchanged if the credentials ever come from Vault, another
// CI's secret store, or a shell somebody exported by hand. The encryption
// choice stays swappable because there is exactly one place that creates
// plaintext and one that destroys it.
//
// Values are passed in the environment rather than written to disk. The
// exceptions are the three that a tool can only open as a file — the Android
// keystore, the App Store Connect key and the distribution certificate — and
// each is materialized into a private temp directory that is removed however
// this exits.
//
// The identity is never in the repository. Locally it is
// ~/.config/sops/age/keys.txt; in CI it is the single SOPS_AGE_KEY secret, so
// switching CI provider means moving one value.
import 'dart:convert';
import 'dart:io';

import 'package:yaml/yaml.dart';

import 'project.dart';

/// A credential group: some keys only make sense together.
///
/// Modeled rather than checked ad hoc because a *partial* group is the
/// dangerous state. A keystore path with no password does not fail as "you
/// forgot the password" — Gradle falls through to the debug key and produces an
/// artifact that only Play rejects, after a full upload. The same shape as the
/// "all four or none" rule in the consuming build.gradle.kts, and for the same
/// reason.
class _Group {
  const _Group(this.name, {required this.required, this.optional = const []});

  final String name;
  final List<String> required;
  final List<String> optional;

  List<String> get keys => [...required, ...optional];
}

const _groups = [
  _Group(
    'the Android upload key',
    required: ['keystore_p12_base64', 'keystore_password', 'key_alias'],
    // PKCS12 uses one password for the store and the key alike, so this is
    // almost never set — but a keystore with a genuinely separate key password
    // slots straight in, and Gradle needs no special case either way.
    optional: ['key_password'],
  ),
  _Group(
    'the Play service account',
    required: ['play_service_account_json_base64'],
  ),
  _Group(
    'the App Store Connect API key',
    required: ['api_key_id', 'api_private_key_base64'],
    // Optional, and leaving it out means something. A *team* key has an issuer
    // id; an *individual* key is generated by one App Store Connect user,
    // inherits that user's app restrictions, and has none at all. Requiring it
    // — as the shell version did — makes the scoped-to-one-app credential
    // unusable, which is the one worth having in CI.
    optional: ['api_issuer_id'],
  ),
  _Group(
    'the Apple distribution certificate',
    required: ['distribution_p12_base64', 'distribution_p12_password'],
  ),
];

/// Every key any group names. Anything else in the file is an error.
final _knownKeys = {for (final g in _groups) ...g.keys};

/// The block sops writes to record its own recipients and MAC.
///
/// Present in the encrypted file and stripped by `sops -d`, so it is skipped
/// when reading a file that has not been decrypted and never appears in one
/// that has.
const _sopsMetadataKey = 'sops';

/// One credential name found in a secrets file, and whether it is accepted.
typedef SecretKey = ({String name, String? group, bool recognized});

/// The credential names in [secretsFile], **without decrypting it**.
///
/// A sops-encrypted file keeps its keys in cleartext and encrypts only the
/// values, so the shape of one can be read with no identity and no risk of a
/// secret reaching a terminal — which makes this the check to run *before*
/// adopting a new version, since an unrecognized key stops `secrets exec` dead.
///
/// **It shares [_walkLeaves] with the parser that enforces this**, which is the
/// only reason it can be trusted: a pre-flight check that approximates the real
/// rules is a pre-flight check that eventually disagrees with them. This
/// replaced a `grep` recommended in the skill, whose character class omitted
/// digits and so hid `keystore_p12_base64`, `api_private_key_base64` and every
/// other name carrying actual key material — reporting the four that mattered
/// least and reading as a clean bill of health.
List<SecretKey> inspectSecretKeys(File secretsFile) {
  if (!secretsFile.existsSync()) {
    throw ProjectException('no ${secretsFile.path}');
  }
  final dynamic document;
  try {
    document = loadYaml(secretsFile.readAsStringSync());
  } on YamlException catch (e) {
    // `e.message` for the same reason as the decrypting parser below, even
    // though this one reads the *encrypted* file and would normally echo
    // nothing but ciphertext. The case it covers is a file that has been
    // written and not yet encrypted — checking its shape before running `sops
    // -e` is exactly what somebody would do — where the source line a parse
    // error quotes is plaintext.
    throw ProjectException(
      '${secretsFile.path} is not valid YAML: ${e.message}',
    );
  }
  if (document is! YamlMap) {
    throw ProjectException(
      '${secretsFile.path} must be a mapping of credentials',
    );
  }

  final found = <SecretKey>[];
  _walkLeaves(
    document,
    secretsFile.path,
    skipMetadata: true,
    onLeaf: (key, _, group) => found.add((
      name: key,
      group: group.isEmpty ? null : group,
      recognized: _knownKeys.contains(key),
    )),
  );
  found.sort((a, b) => a.name.compareTo(b.name));
  return found;
}

/// Every credential name `secrets exec` accepts, sorted.
List<String> knownSecretKeys() => _knownKeys.toList()..sort();

/// Calls [onLeaf] for every credential in [document], walking exactly one level
/// of grouping.
///
/// **Headings are allowed and carry no meaning.** A real file groups its
/// credentials — `android:` and `apple:` — because that is how somebody reads
/// it, and the shell script this replaces coped by stripping leading whitespace
/// before matching, which made it indentation-blind by accident. Reading only
/// the top level instead would refuse every such file, having found none of the
/// credentials in it.
///
/// So the heading is discarded. The names that matter are the leaves, which is
/// what the credential groups are declared in terms of — a credential does not
/// become a different credential because of the heading it was filed under.
void _walkLeaves(
  YamlMap document,
  String path, {
  required void Function(String key, Object? value, String group) onLeaf,
  bool skipMetadata = false,
}) {
  for (final entry in document.entries) {
    final key = '${entry.key}';
    final value = entry.value;
    if (skipMetadata && key == _sopsMetadataKey) {
      continue;
    }
    if (value is YamlMap) {
      for (final child in value.entries) {
        if (child.value is YamlMap || child.value is YamlList) {
          throw ProjectException(
            '$path nests $key.${child.key} deeper than a credential goes — '
            'headings may group values, but only one level down',
          );
        }
        onLeaf('${child.key}', child.value, key);
      }
    } else {
      onLeaf(key, value, '');
    }
  }
}

/// What was decrypted, and where the files it had to write went.
class LoadedSecrets {
  LoadedSecrets(this.environment, this.loaded, this._work);

  /// The child's environment: this process's, plus the credentials.
  final Map<String, String> environment;

  /// The groups that were present, for reporting. Naming what was loaded
  /// rather than what was asked for is what makes a credential that silently
  /// did not arrive visible instead of inferred.
  final List<String> loaded;

  final Directory _work;

  void dispose() {
    if (_work.existsSync()) {
      _work.deleteSync(recursive: true);
    }
  }
}

/// Locates the `sops` binary: the project's `.bin` first, then PATH.
String findSops(String repoRoot) {
  final local = File('$repoRoot/.bin/sops');
  if (local.existsSync()) {
    return local.path;
  }
  final which = Process.runSync('sh', ['-c', 'command -v sops']);
  final found = (which.stdout as String).trim();
  if (which.exitCode == 0 && found.isNotEmpty) {
    return found;
  }
  throw ProjectException(
    'sops not found — run `cux_ship deps install`, or put sops on PATH',
  );
}

/// Decrypts [secretsFile] and returns the environment a child should get.
///
/// Nothing is written outside the temp directory held by the result, and the
/// caller must [LoadedSecrets.dispose] it.
LoadedSecrets loadSecrets({
  required String repoRoot,
  required File secretsFile,
}) {
  if (!secretsFile.existsSync()) {
    throw ProjectException('no ${secretsFile.path}');
  }
  final sops = findSops(repoRoot);

  // sops looks for an identity in SOPS_AGE_KEY, SOPS_AGE_KEY_FILE and a
  // platform-specific default that is ~/Library/Application Support/sops/age on
  // macOS. Pointing at the XDG path explicitly keeps one location working on
  // both, and leaves an already-set variable — which is how CI supplies it —
  // alone.
  final sopsEnvironment = <String, String>{};
  final home = Platform.environment['HOME'];
  if (Platform.environment['SOPS_AGE_KEY'] == null &&
      Platform.environment['SOPS_AGE_KEY_FILE'] == null &&
      home != null) {
    final identity = File('$home/.config/sops/age/keys.txt');
    if (identity.existsSync()) {
      sopsEnvironment['SOPS_AGE_KEY_FILE'] = identity.path;
    }
  }

  final result = Process.runSync(sops, [
    '-d',
    secretsFile.path,
  ], environment: sopsEnvironment);
  if (result.exitCode != 0) {
    throw ProjectException(
      'could not decrypt ${secretsFile.path} — no usable age identity.\n'
      '    Locally:  ~/.config/sops/age/keys.txt\n'
      '    In CI:    set SOPS_AGE_KEY to the private key',
    );
  }

  final values = _parse(result.stdout as String, secretsFile.path);

  // 0700 by construction — createTempSync uses mkdtemp. The files below are
  // narrowed explicitly anyway, because they inherit this process's umask
  // rather than the directory's mode.
  final work = Directory.systemTemp.createTempSync('cux_ship_secrets');
  try {
    return _materialize(values, work);
  } on Object {
    work.deleteSync(recursive: true);
    rethrow;
  }
}

Map<String, String> _parse(String plaintext, String path) {
  final dynamic document;
  try {
    document = loadYaml(plaintext);
  } on YamlException catch (e) {
    // `e.message` and not `$e`. A YamlException stringifies with the offending
    // source line and a caret under it — and what this parses is the
    // *decrypted* document, so the whole exception puts key material on stderr
    // and into whatever log is capturing it. The bare reason says as much about
    // what to fix and discloses nothing.
    throw ProjectException('$path did not decrypt to valid YAML: ${e.message}');
  }
  if (document is! YamlMap) {
    throw ProjectException('$path must be a mapping of credentials');
  }

  final values = <String, String>{};
  final unknown = <String>[];
  final seenUnder = <String, String>{};

  void leaf(String key, Object? value, String group) {
    final where = group.isEmpty ? key : '$group.$key';
    if (!_knownKeys.contains(key)) {
      unknown.add(where);
      return;
    }
    if (seenUnder.containsKey(key)) {
      throw ProjectException(
        '$path names $key twice, under ${seenUnder[key]} and $group — which '
        'one wins is not something to guess at with a credential',
      );
    }
    if (value == null) {
      return;
    }
    // Scalars are stringified rather than type-checked: a key alias that is
    // all digits parses as an int, and refusing it would be pedantry.
    values[key] = '$value';
    seenUnder[key] = group.isEmpty ? '(top level)' : group;
  }

  // Shared with `inspectSecretKeys`, deliberately: what counts as a credential
  // name has to be one answer, or the check somebody runs before adopting a
  // version disagrees with the parser that refuses them.
  //
  // No metadata to skip here — `sops -d` strips its own block, so a decrypted
  // file never carries one, and a `sops:` key in a plaintext file is an
  // unrecognized name worth reporting rather than ignoring.
  _walkLeaves(document, path, onLeaf: leaf);

  // An unrecognized key is a typo, and a typo here is silent: the credential
  // simply never arrives, the build falls back to a debug key or an anonymous
  // API call, and the failure surfaces at the store.
  if (unknown.isNotEmpty) {
    unknown.sort();
    throw ProjectException(
      '$path has ${unknown.length == 1 ? 'an unrecognized key' : 'unrecognized keys'}: '
      '${unknown.join(', ')}\n'
      '    known keys: ${(_knownKeys.toList()..sort()).join(', ')}',
    );
  }
  return values;
}

LoadedSecrets _materialize(Map<String, String> values, Directory work) {
  final environment = Map<String, String>.from(Platform.environment);
  final loaded = <String>[];

  for (final group in _groups) {
    final present = group.keys.where(values.containsKey).toList();
    if (present.isEmpty) {
      continue;
    }
    final missing = group.required.where((k) => !values.containsKey(k));
    if (missing.isNotEmpty) {
      throw ProjectException(
        '${group.name} is half configured — ${missing.join(', ')} '
        '${missing.length == 1 ? 'is' : 'are'} missing.\n'
        'Set all of ${group.required.join(', ')}, or none of them: a partial '
        'set fails at the store rather than here.',
      );
    }
    loaded.add(group.name);
  }

  if (values.containsKey('keystore_p12_base64')) {
    final keystore = _writeBase64(
      work,
      'upload.p12',
      values['keystore_p12_base64']!,
      'keystore_p12_base64',
    );
    environment['ANDROID_KEYSTORE_PATH'] = keystore.path;
    environment['ANDROID_KEYSTORE_PASSWORD'] = values['keystore_password']!;
    environment['ANDROID_KEY_ALIAS'] = values['key_alias']!;
    environment['ANDROID_KEY_PASSWORD'] =
        values['key_password'] ?? values['keystore_password']!;
  }

  if (values.containsKey('play_service_account_json_base64')) {
    // Stored base64-encoded because the service account is itself JSON, and
    // nesting raw JSON inside a YAML scalar invites quoting bugs for no
    // benefit. It goes to the child as the JSON itself.
    environment['GOOGLE_PLAY_SERVICE_ACCOUNT_JSON'] = utf8.decode(
      _decode(
        values['play_service_account_json_base64']!,
        'play_service_account_json_base64',
      ),
    );
  }

  if (values.containsKey('api_key_id')) {
    final keyId = values['api_key_id']!;
    // The directory name is not decoration. `altool --apiKey` does not take a
    // path: it looks for AuthKey_<id>.p8 in ./private_keys, ~/private_keys,
    // ~/.private_keys, ~/.appstoreconnect/private_keys, or
    // $API_PRIVATE_KEYS_DIR. So the file has to be named after the key and live
    // in a directory altool will search, and the last of those is the only one
    // that is not a fixed location in somebody's home.
    final keys = Directory('${work.path}/private_keys')..createSync();
    final p8 = _writeBase64(
      keys,
      'AuthKey_$keyId.p8',
      values['api_private_key_base64']!,
      'api_private_key_base64',
    );
    environment['APPLE_API_KEY_ID'] = keyId;
    // For cux_ship_appstore and for `xcodebuild -authenticationKeyPath`, both
    // of which do take a path.
    environment['APPLE_API_PRIVATE_KEY_PATH'] = p8.path;
    environment['API_PRIVATE_KEYS_DIR'] = keys.path;
    final issuer = values['api_issuer_id'];
    if (issuer != null) {
      environment['APPLE_API_ISSUER_ID'] = issuer;
    }
  }

  if (values.containsKey('distribution_p12_base64')) {
    final cert = _writeBase64(
      work,
      'distribution.p12',
      values['distribution_p12_base64']!,
      'distribution_p12_base64',
    );
    environment['APPLE_DISTRIBUTION_P12_PATH'] = cert.path;
    environment['APPLE_DISTRIBUTION_P12_PASSWORD'] =
        values['distribution_p12_password']!;
  }

  return LoadedSecrets(environment, loaded, work);
}

List<int> _decode(String value, String key) {
  try {
    return base64.decode(value.trim());
  } on FormatException {
    throw ProjectException('$key is not valid base64');
  }
}

File _writeBase64(Directory dir, String name, String value, String key) {
  final bytes = _decode(value, key);
  if (bytes.isEmpty) {
    throw ProjectException('$key decodes to nothing');
  }
  final file = File('${dir.path}/$name')..writeAsBytesSync(bytes);
  // Explicit rather than trusting the umask: this is a private key, and the
  // directory being 0700 is only half of it on a machine whose umask is 022.
  Process.runSync('chmod', ['600', file.path]);
  return file;
}

/// Runs [command] with the credentials from [secretsFile] in its environment,
/// and returns its exit code.
///
/// The child runs with the **repository root** as its working directory, the
/// same frame of reference the rest of the tool uses — `cux_ship` is normally
/// invoked from `tool/cux_ship`, and a command like `tool/build.sh android`
/// would not resolve from there.
Future<int> runSecretsExec({
  required String repoRoot,
  required File secretsFile,
  required List<String> command,
}) async {
  if (command.isEmpty) {
    throw ProjectException(
      'nothing to run — put the command after `--`, as in\n'
      '    cux_ship secrets exec -- tool/build.sh --release android',
    );
  }

  final secrets = loadSecrets(repoRoot: repoRoot, secretsFile: secretsFile);
  try {
    // To stderr, so `cux_ship secrets exec -- env | grep …` pipes the child's
    // output and not this. What was *loaded* rather than what was asked for:
    // a credential that silently did not arrive has to be visible here rather
    // than inferred from a failure three minutes later.
    stderr.writeln(
      '==> loaded ${secrets.loaded.isEmpty ? 'nothing' : secrets.loaded.join(', ')}\n'
      '==> running ${command.join(' ')} in $repoRoot',
    );

    final process = await Process.start(
      command.first,
      command.skip(1).toList(),
      environment: secrets.environment,
      workingDirectory: repoRoot,
      mode: ProcessStartMode.inheritStdio,
    );

    // Watched so the VM does not die on Ctrl-C without cleaning up — the
    // default behavior terminates immediately and would leave a decrypted
    // private key in the temp directory. The signal is forwarded rather than
    // acted on here, so the child gets to exit and the ordinary path below
    // does the removal.
    final signals = [
      ProcessSignal.sigint.watch().listen((s) => process.kill(s)),
      ProcessSignal.sigterm.watch().listen((s) => process.kill(s)),
    ];
    try {
      return await process.exitCode;
    } finally {
      for (final subscription in signals) {
        await subscription.cancel();
      }
    }
  } finally {
    // Not `exec`, and this is why: replacing this process would mean nothing
    // ever ran the cleanup, leaving a decrypted private key behind on every
    // invocation.
    secrets.dispose();
  }
}
